name: Finding humanity
favicon: null
layout_spectrum: 1
typography_spectrum: 0.613828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#F4F5F1'
    - '#9A886E'
    - '#CFE002'
    - '#287791'
  brandStrength: 1
  lightness: 0.3220911
  saturation: 0.8212479
  rhythmicContrast: 0.8524452
purpose: []
